micronaut:
  application:
    name: mn
datasources:
  default:
    driverClassName: "org.testcontainers.jdbc.ContainerDatabaseDriver"
    url: "jdbc:tc:postgresql:14.2:///postgres"
    username: user
    password: password
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  datasources:
    default:
      change-log: 'classpath:/changelog.yml'
